apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-strip-prefix
    app.kubernetes.io/part-of: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.routing.ingressRouteApi.pathPrefix }}
