apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
  labels:
    {{- include "gitlab-sa.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
type: kubernetes.io/service-account-token
